Fix/data format
kubo11/bajo-taio pull request #14
Opened 2023-11-24 01:49 UTC by kubo11

2023-11-24 19:39 UTC, rumanowskak requested changes
Wszystko wygląda okej, zostawiłam tylko mały komentarz odnośnie mojej części bo teraz przy okazji tych zmian zauważyłam, że w sumie w jedna rzecz powinna być nieco inna

2023-11-24 19:39 UTC, rumanowskak commented on src/graph.c
>    graph->in_degrees[end]++;
```suggestion
  graph->out_degrees[beg] += edges_count;
  graph->in_degrees[end] += edges_count;
```

Teraz zuważyłam, że tutaj w sumie powinno być `+= edges_count` zamiast `++`. Wcześniej każda krawędź w sumie była dodawana osobno przy wczytywaniu z konsoli czy plików, więc to nie miało znaczenia, ale powinno być w ten sposób.

2023-11-28 21:49 UTC, mateusztobiasz approved these changes

2023-11-28 21:49 UTC, mateusztobiasz commented on include/graph.h
> +bool is_single_graph(FILE *in);
Tutaj, jak rozmawialiśmy, można rozważyć zmianę nazwy na coś w stylu is_graphs_number_set czy is_graphs_number_given

2023-11-29 14:50 UTC, rumanowskak approved these changes

2023-11-29 20:55 UTC, merged