Add metric calculation
kubo11/bajo-taio pull request #3
Opened 2023-11-09 19:56 UTC by rumanowskak

2023-11-09 21:08 UTC, sebastianSzarafin commented on src/graph.c
> +  for (uint32_t v = 1; v < graph->vertices + 1; ++v)
Jest sens dzielić to liczenie max degree na out max i in max skoro koniec końców i tak zwracamy większą z 2 wartości?

2023-11-09 21:08 UTC, sebastianSzarafin commented on src/graph.c
> +{
Znowu, jest sens dzielić obliczenia na 2 pętle? + może wygodniej by po prostu zwracać distribution z funkcji ale to tylko taka sugestia

2023-11-09 21:08 UTC, sebastianSzarafin commented on src/graph.c
> +{
A i chyba by można to distribution zrobić normalnie na stosie i nie bawić się w te alokacje pamięci (?)

2023-11-13 14:02 UTC, kubo11 approved these changes

2023-11-13 23:32 UTC, kubo11 requested changes

2023-11-13 23:32 UTC, kubo11 commented on Makefile
> +	@mkdir -p $(BUILDDIR)
To nie działa pod windowsem. Mkdir nie ma flagi -p, a bez niej failuje jeśli katalog build już istnieje.

2023-11-14 18:42 UTC, merged